export function getDom() {
  return {
    form: document.getElementById("task-form"),
    titleInput: document.getElementById("task-title"),
    descriptionInput: document.getElementById("task-description"),
    boardName: document.getElementById("board-name"),

    helpToggleButton: document.getElementById("help-toggle"),
    emojiToggleButton: document.getElementById("emoji-toggle"),
    helpModalOverlay: document.getElementById("help-modal-overlay"),
    helpCloseButton: document.getElementById("help-close-btn"),
    helpExportPromptButton: document.getElementById("help-export-prompt-btn"),
    emojiModalOverlay: document.getElementById("emoji-modal-overlay"),
    emojiCloseButton: document.getElementById("emoji-close-btn"),
    emojiGrid: document.getElementById("emoji-grid"),
    emojiCopyStatus: document.getElementById("emoji-copy-status"),
    authToggleButton: document.getElementById("auth-toggle"),
    authStatus: document.getElementById("auth-status"),
    authModalOverlay: document.getElementById("auth-modal-overlay"),
    authCloseButton: document.getElementById("auth-close-btn"),
    authCancelButton: document.getElementById("auth-cancel-btn"),
    authForm: document.getElementById("auth-form"),
    authEmailInput: document.getElementById("auth-email"),
    authPasswordInput: document.getElementById("auth-password"),
    authModeButton: document.getElementById("auth-mode-btn"),
    authToggleText: document.getElementById("auth-toggle-text"),
    authSubmitButton: document.getElementById("auth-submit-btn"),
    authError: document.getElementById("auth-error"),
    authModalTitle: document.getElementById("auth-modal-title"),
    authModalSubtitle: document.getElementById("auth-modal-subtitle"),
    usernameModalOverlay: document.getElementById("username-modal-overlay"),
    usernameForm: document.getElementById("username-form"),
    usernameInput: document.getElementById("username-input"),
    usernameError: document.getElementById("username-error"),
    usernameModalTitle: document.getElementById("username-modal-title"),
    usernameModalSubtitle: document.getElementById("username-modal-subtitle"),
    usernameSaveButton: document.getElementById("username-save-btn"),
    usernameSkipButton: document.getElementById("username-skip-btn"),

    settingsToggleButton: document.getElementById("settings-toggle"),
    settingsMenu: document.getElementById("settings-menu"),
    settingsColumnsToggleButton: document.getElementById("settings-columns-toggle"),
    settingsChangeUsernameButton: document.getElementById("settings-change-username"),
    settingsExportBackupButton: document.getElementById("settings-export-backup"),
    settingsImportBackupButton: document.getElementById("settings-import-backup"),
    boardToggleButton: document.getElementById("board-toggle"),

    boardsOverlay: document.getElementById("boards-overlay"),
    boardsTitle: document.getElementById("boards-title"),
    boardsTablesSection: document.getElementById("boards-tables-section"),
    boardsColumnsSection: document.getElementById("boards-columns-section"),
    boardsBackupSection: document.getElementById("boards-backup-section"),
    boardsCloseButton: document.getElementById("boards-close"),
    boardsList: document.getElementById("boards-list"),
    newBoardInput: document.getElementById("new-board-input"),
    createBoardButton: document.getElementById("create-board-btn"),
    columnsList: document.getElementById("columns-list"),
    columnsDangerSlot: document.getElementById("columns-danger-slot"),
    newColumnInput: document.getElementById("new-column-input"),
    createColumnButton: document.getElementById("create-column-btn"),
    exportBackupButton: document.getElementById("export-backup-btn"),
    importBackupButton: document.getElementById("import-backup-btn"),
    backupFileInput: document.getElementById("backup-file-input"),
    backupStatus: document.getElementById("backup-status"),

    iaGenerateButton: document.getElementById("ia-generate-btn"),
    aiModalOverlay: document.getElementById("ai-modal-overlay"),
    aiPlanInput: document.getElementById("ai-plan-input"),
    aiCancelButton: document.getElementById("ai-cancel-btn"),
    aiGenerateConfirmButton: document.getElementById("ai-generate-confirm-btn"),
    aiCloseButton: document.getElementById("ai-close-btn"),

    taskModalOverlay: document.getElementById("task-modal-overlay"),
    taskModalClose: document.getElementById("task-modal-close"),
    taskModalCancel: document.getElementById("task-modal-cancel"),
    taskModalSave: document.getElementById("task-modal-save"),
    taskEditTitle: document.getElementById("task-edit-title"),
    taskEditDescription: document.getElementById("task-edit-description"),
    taskEditCategory: document.getElementById("task-edit-category"),
    taskEditAssignee: document.getElementById("task-edit-assignee"),
    taskEditTags: document.getElementById("task-edit-tags"),
    taskEditDeadline: document.getElementById("task-edit-deadline"),
    taskEditCompletedAt: document.getElementById("task-edit-completed-at"),
    taskEditPriority: document.getElementById("task-edit-priority"),

    themeToggleButton: document.getElementById("theme-toggle"),
    themeIcon: document.getElementById("theme-icon"),
    themeLabel: document.getElementById("theme-label"),
    focusToggleButton: document.getElementById("focus-toggle"),
    focusLabel: document.getElementById("focus-label"),

    boardElement: document.querySelector(".board"),
    appRoot: document.querySelector(".app"),
    appMainScroll: document.querySelector(".app-main-scroll"),
  };
}
